fac_app/urls.py
from django.urls import path
from fac_app.views import *

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('add-customer', AddCustomerView.as_view(), name='add-customer')
]

facture_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fac_app.urls')),
]

if settings.DEBUG:

    urlpatterns+=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

fac_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    """
    Name: Customer model definition
    """
    SEX_TYPES = (
        ('M', 'Masculin'),
        ('F', 'Feminin')
    )
    name=models.CharField(max_length=132)

    email = models.EmailField()

    phone = models.CharField(max_length=132)

    address = models.CharField(max_length=64)

    sex = models.CharField(max_length=1, choices=SEX_TYPES)

    age = models.CharField(max_length=12)

    city = models.CharField(max_length=32)

    zip_code = models.CharField(max_length=16)

    created_date = models.DateTimeField(auto_now_add=True)

    save_by = models.ForeignKey(User, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        return self.name
    
class Invoice(models.Model):
    """
    Name: Invoice model definition
    Description:
    author: camaracodeur.pro@gmail.com
    """

    INVOICE_TYPE = (
        ('R', 'RECU'),
        ('P', 'PROFORMA FACTURE'),
        ('F', 'FACTURE')
        
    )
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)

    save_by = models.ForeignKey(User, on_delete=models.PROTECT)

    invoice_date_time = models.DateTimeField(auto_now_add=True)

    total = models.DecimalField(max_digits=10000, decimal_places=2)
    
    last_update_date = models.DateTimeField(null=True, blank=True)

    paid = models.BooleanField(default=False)

    invoice_type = models.CharField(max_length=1, choices=INVOICE_TYPE)

    comments = models.TimeField(null=True,max_length=1000, blank=True)


    class Meta:
        verbose_name = "Invoice"
        verbose_name_plural = "Invoices"
    def __str__(self):
        return f"{self.customer.name} {self.invoice_date_time}"
    @property
    def get_total(self):
        articles = self.article_set.all()
        total = sum(article.get_total for article in articles)
    
class Article(models.Model):
    """
    Name: Article model definition
    Description:
    Author: camaracodeur.pro@gmail.com
    """
    invoice =models.ForeignKey(Invoice, on_delete=models.CASCADE)

    name = models.CharField(max_length=32)

    quantity = models.IntegerField()

    unit_price = models.DecimalField(max_digits=1000, decimal_places=2)

    total = models.DecimalField(max_digits=1000, decimal_places=2)

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    @property
    def get_total(self):
        total = self.quantity * self.unit_price 

fac_app/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views import View
from .models import*

# Create your views here.

class HomeView(View):
    """Main View"""

    templates_name = 'index.html'

    invoices = Invoice.objects.all()
    
    context = {
        'invoices': invoices
    }

    def get(self, request, *args, **kwags):
        return render(request, self.templates_name, self.context)
    
    def post(self, request, *args, **kwags):
        return render(request, self.templates_name, self.context)
    

class AddCustomerView(View):
    """  add new customer """

    template_name = 'add_customer.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
    def post(self, request, *args, **kwargs):
        data = {
            'name': request.POST.get('name'),
            'email': request.POST.get('email'),
            'phone': request.POST.get('phone'),
            'address': request.POST.get('address'),
            'sex': request.POST.get('sex'),
            'age': request.POST.get('age'),
            'city': request.POST.get('city'),
            'zip_code': request.POST.get('zip'),
            'save_by': request.user
        }
        try:
            created = Customer.objects.create(**data)

            if created:
                messages.success(request, f"Customer {request.POST.get('name')} created successfuly.")
            else:
                messages.error(request, "Sorry, please try again the sent data is corrupt")

        except Exception as e:
            messages.error(request, f"Sorry our system is detecting the following issues {e}.")

        return render(request, self.template_name)

templates/add_customer.html
{% extends "base.html" %}

{% block content %}


<br><br><br><br>

<h1 class="text-capitalize text-center mx-10 bg-dark text-white">Register a new customer</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="name">Name</label>
            <input name="name" required type="text" class="form-control" id="name" placeholder="customer first and last name">
        </div>

        <div class="form-group col-md-4">
            <label for="email">Email</label>
            <input name="email" required type="email" class="form-control" id="email" placeholder="customer email address">
        </div>

        <div class="form-group col-md-2">
            <label for="phone">Phone</label>
            <input name="phone" required type="number" class="form-control" id="phone" placeholder="customer phone number">
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="sex">Sex</label>
            <select name="sex"class="form-control" required id="sex">
                <option>Choose the gender...</option>
                <option value="M">Male</option>
                <option value="F">Feminine</option>
            </select>
        </div>

        <div class="form-group col-md-6">
            <label for="age">Age</label>
            <select name="age"  class="form-control" required id="age">
                <option>Choose the age range ...</option>
                <option value="0-15">0-15</option>
                <option value="15-25">0-25</option>
            </select>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="address">Address</label>
            <input type="text" name="address" class="form-control" required id="address" placeholder="customer address">
        </div>
    </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="city">City</label>
                <input name="city" required type="text" class="form-control" id="city" placeholder="customer city">
            </div>

            <div class="form-group col-md-6">
                <label for="zip">Zip code</label>
                <input name="zip" required type="number" class="form-control" id="zip" placeholder="zip code">
            </div>
        </div>
    
    <button type="submit" class="btn btn-primary">Save</button>
</form>
<br><br><br>
{% endblock content %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Gestion-Facture</title>
</head>
<body>

    <!-- header -->
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">INVOICE SYSTEME</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                          Langue
                        </a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="#">English</a>
                          <a class="dropdown-item" href="#">French</a>
                        </div> 
                      </li>
          
                    </ul>
                   
                  </div>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                        More option
                      </a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'add-customer'%}">Add customer</a>
                        <a class="dropdown-item" href="#">Add admin</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">statistic</a>
                        
                        
                      </div>
                    </li>
        
                  </ul>
                 
                </div>
              </nav>
        </header>
        <div class="container">
          <div class="wrapper">
            <br>
            {% for message in messages%}
            <div class="alert {{message.tags}} alert-dismissible " role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              {{message|safe}}
            </div>
            {%endfor%}
          </div>
        </div>

    <!-- endheader -->

        <div class="container">
            
            {% block content %}
            
            {% endblock content %}
        </div>


        <!-- footer -->
        <footer class="bg-light text-center text-dark">

        <!-- copyright -->
          <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            invoice system © 2023 copyright:
            <a href="https://www.youtube.com/channel/UC9utGfO6okRXqeKgHk29Wew">CamaraPro</a>
          </div>

        <!-- end copyright -->
        
        </footer>

        <!-- end footer -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html> 

templates/index.html
{% extends "base.html" %}
{% load static %}



{% block content %}
<br><br>

<div class="row">
   <a href="" class="btn col-md-4 btn-primary">
      Register a new invoice<span class="badge text-bg-secondary"></span>
   </a>

   <a href='#' class="col-md-4">
      <span class="badge text-bg-secondary"></span>
   </a>

   <a href="{% url 'add-customer'%}" class="btn col-md-4 btn-primary">
       Register a new customer<span class="badge text-bg-secondary"></span>
   </a>

</div>

<br> <br>

<div class="form-group ">
   <input id="search" class="form-control" type="text" placeholder="Search....">
</div>

<div>
   <table class="table table-striped-columns">
      <thead>
         <tr>
            <th scope="col">#</th>
            <th scope="col">CUSTOMERS NAME</th>
            <th scope="col">DATE</th>
            <th scope="col">TOTAL</th>
            <th scope="col">PAID</th>
            <th scope="col">TYPE OF INVOICE</th>
            <th scope="col">ACTION</th>
         </tr>
      </thead>
      <tbody id="myTable">
         {% if invoices %}
         {% for facture in invoices %}
         <tr>
            <th scope="row">{{ facture.pk }}</th>
            <td>{{facture.customer.name}}</td>
            <td>{{facture.invoice_date_time}}</td>
            <td>{{ facture.get_total }}</td>
            <td>
               {% if facture.paid %}
               <img src="{% static 'images/icon-yes.svg' %}" alt="True">
               {% else %}
               <img src="{% static 'images/icon-no.svg' %}" alt="False">
               {% endif %}
            </td>
            <td>{{facture.get_invoice_type_display }}</td>
            <td>
               <a href="" title="Detail" class="badge text-white bg-success">View</a>

               <button id="btn-invoice-sup" type="button" data-toggle="modal" data-target="#supprimer"
                  class="badge text-white bg-danger" title="Supprimer" data-id="{{ facture.pk }}"
                  data-customer="{{facture.customer.name}}">Delete
               </button>

               <button id="btn-invoice-mod" type="button" data-toggle="modal" title="Modifier" data-target="#modifier"
                  data-id="{{facture.pk}}" data-customer="{{facture.customer.name}}"
                  class="badge text-dark bg-warning">Modify
               </button>
            </td>
         </tr>

         {% endfor %}

         {% else %}
         
         <p class="text-center text-white">No invoice found.</p>
         {% endif %}


      </tbody>

   </table>
</div>

<!-- Modal modifier -->
<div class="modal fade" id="modifier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark text-center" id="exampleModalLabel">Modification</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <form method="post">
            {% csrf_token %}
            <div class="modal-body">

               <input name="id_modified" type="hidden" id="id_modified">

               <label id="label_id" class="text-dark checkbox-inline"> <strong id="strong_id"> This bill has been paid?</strong></label>

               <input type="radio" id="html" name="modified" value="True">
               <label class="text-white bg-primary" for="html">Yes</label>

               <input type="radio" id="css" name="modified" value="False">
               <label class="text-white bg-danger" for="css">No</label><br>

            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <button type="submit" class="btn btn-primary">Save</button>
            </div>
         </form>
      </div>
   </div>
</div>
<!-- end modal-->

<!-- Modal suppression -->
<div class="modal fade" id="supprimer" tabindex="-1" role="dialog" aria-labelledby="sexampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark" id="sexampleModalLabel">Delete Invoice</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form method="post">
               {% csrf_token %}
               <input name="id_supprimer" type="hidden" id="id_supprimer">
               <label id="label_id_s" class="text-dark checkbox-inline"> <strong id="strong_id_s">Are you sure you want to delete the invoice  ?</strong></label>

               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
               </div>
            </form>
         </div>

      </div>
   </div>
</div>
<!-- end modal-->

<br><br>

<script type="text/javascript">

   // modification

   $(document).on('click', '#btn-invoice-mod', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_modified').val(invoice_id);

   })

   // deleting of invoice

   $(document).on('click', '#btn-invoice-sup', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_supprimer').val(invoice_id);

   })



</script>


<script>

   $(document).ready(function(){
      $("#search").on("keyup", function(){
         var value = $(this).val().toLowerCase();
         $("#myTable tr").filter(function(){
            $(this).toggle($(this).text().toLocaleLowerCase().indexOf(value)>-1)
         });
      });
   });

</script>



{% endblock %}